### ISSUE TITLE
Unable to set presets with RGB values

### ISSUE THREAD

**Issue by 420pootang69** [martynasS/magic-home-desktop#29] opened 2022-02-05 14:14 UTC
Hi!

Love that you did this. Will save me pulling my phone out to change the lighting!

On the 'official' Magic Home app, you can set your presets using RGB values, instead of the colour wheel. Could we get this added?

It's especially important to me, as I have a janky setup with warm white LEDs in the blue channel, so the colour wheel makes little sense. I have the RGB (actually RGW I suppose) values I use saved though.

Thanks for your effort!

(I can't figure out how to tag this an enhancement by the way.)

**Comment by martynaskre** [comment] 2022-07-19 19:31
Duplicate of #25.

**Closed as completed by martynaskre** 2022-07-19 19:31 UTC
