### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EhalloMatt** [martynasS/magic-home-desktop#32] opened 2022-05-15 02:55 UTC
**Describe the bug**
If I open Magic Control I am unable to see my devices and the aligning of the window isn't correct either.
**To Reproduce**
1. Go to 'Taskbar'
2. Click on 'Magic Control'
3. See error

**Expected behavior**
I expected to see my lights and the application to be opened correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/40703994/168455049-cec8d554-7e0d-4988-b5d7-bff5b5d8de15.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-Bit
 - Version:10.0.19044 Build 19044
 - Release 21H2

**Additional context**
I can't see any of my devices and the application doesn't work due to the way it application opens.

**Comment by martynaskre** [comment] 2022-07-18 13:06
Duplicate of #15

**Closed as completed by martynaskre** 2022-07-18 13:06 UTC
Labels: bug
